name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.10  # Adjust to your Python version
  - numpy
  - matplotlib
  - xarray
  - ipywidgets
  - cartopy
  - netcdf4  # Add this line
  - h5netcdf  # Add this line
